services:
  # Servicio de la aplicación Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    # ESTA LÍNEA ES NUEVA:
    # Le dice a 'app' que espere a que 'db' esté "healthy"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306" # Puerto corregido
    environment:
      MYSQL_ROOT_PASSWORD: "R00tP@ssw0rd31415"
      MYSQL_DATABASE: "FinanzaPersonales_db"
    volumes:
      - mysql_data:/var/lib/mysql
    # ESTE BLOQUE ES NUEVO:
    # Le enseña a Docker cómo saber si MySQL está vivo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-u", "root", "-pR00tP@ssw0rd31415"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: